# Generated by Django 5.0.7 on 2024-07-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crc_ON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_id', models.SmallIntegerField(max_length=4)),
                ('hour', models.SmallIntegerField(max_length=2)),
                ('minute', models.SmallIntegerField(max_length=2)),
                ('status1', models.SmallIntegerField(max_length=1)),
                ('status2', models.SmallIntegerField(max_length=1)),
                ('status3', models.SmallIntegerField(max_length=1)),
                ('status4', models.SmallIntegerField(max_length=1)),
                ('status5', models.SmallIntegerField(max_length=1)),
                ('status6', models.SmallIntegerField(max_length=1)),
            ],
        ),
    ]
