# Generated by Django 5.0.7 on 2024-07-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONsettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crc_on',
            name='circuit_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='hour',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='minute',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='status1',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='status2',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='status3',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='status4',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='status5',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='status6',
            field=models.SmallIntegerField(),
        ),
    ]
