# Generated by Django 5.0.7 on 2024-07-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONsettings', '0003_alter_crc_on_hour_alter_crc_on_minute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crc_on',
            name='circuit_id',
            field=models.IntegerField(default=1001, null=True),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='hour',
            field=models.SmallIntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='minute',
            field=models.SmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='status1',
            field=models.SmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='status2',
            field=models.SmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='status3',
            field=models.SmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='status4',
            field=models.SmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='status5',
            field=models.SmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='crc_on',
            name='status6',
            field=models.SmallIntegerField(default=1, null=True),
        ),
    ]
